import type { ResourceDeposit } from '../../types/game';
import { world } from '../ecs/world';
import { GridMap } from '../grid/GridMap';

export const INITIAL_RESOURCE_DEPOSITS: ResourceDeposit[] = [
  {
    id: 'deposit-0-fish',
    type: 'fish',
    name: 'Королівський рибний ставок',
    regionId: 0,
    gridPosition: [72, 70],
    position: [72.5, 0.05, 70.5],
    currentAmount: 102,
    maxAmount: 102,
    isRich: false,
    seasonalRenewal: true,
    icon: '🐟',
    harvestBuildingLabel: 'Хатина рибалки',
    description: 'Спокійна річкова заплава, багата на пструга, щуку та коропа. Забезпечує жителів свіжою рибою. Відновлюється кожного року.',
  },
  {
    id: 'deposit-0-berries',
    type: 'berries',
    name: 'Багаті ягідні чагарники',
    regionId: 0,
    gridPosition: [42, 68],
    position: [42.5, 0.1, 68.5],
    currentAmount: 128,
    maxAmount: 128,
    isRich: true,
    seasonalRenewal: true,
    icon: '🫐',
    harvestBuildingLabel: 'Хатина збирача ягід',
    description: 'Пишні чагарники дикої чорниці та суниці на теплій галявині. Подвійний запас ягід для швидкого насичення селян у теплий сезон.',
  },
  {
    id: 'deposit-0-stone',
    type: 'stone',
    name: 'Виходи вапняку',
    regionId: 0,
    gridPosition: [88, 45],
    position: [88.5, 0.15, 45.5],
    currentAmount: 300,
    maxAmount: 300,
    isRich: false,
    seasonalRenewal: false,
    icon: '🪨',
    harvestBuildingLabel: 'Каменоломня',
    description: 'Масивні пласти білого вапняку, що виходять на поверхню пагорба. Основне джерело будівельного каменю для міцних споруд.',
  },
  {
    id: 'deposit-0-clay',
    type: 'clay',
    name: 'Поклади гончарної глини',
    regionId: 0,
    gridPosition: [58, 88],
    position: [58.5, 0.08, 88.5],
    currentAmount: 200,
    maxAmount: 200,
    isRich: false,
    seasonalRenewal: false,
    icon: '🏺',
    harvestBuildingLabel: 'Глиняний карʼєр',
    description: 'Вологі теракотові пласти пластичної глини. Необхідні для випалювання якісної покрівельної черепиці та гончарного посуду.',
  },
  {
    id: 'deposit-0-game',
    type: 'wild_game',
    name: 'Королівські мисливські пущі',
    regionId: 0,
    gridPosition: [36, 42],
    position: [36.5, 0.1, 42.5],
    currentAmount: 60,
    maxAmount: 60,
    isRich: true,
    seasonalRenewal: true,
    icon: '🦌',
    harvestBuildingLabel: 'Хатина мисливця',
    description: 'Густі лісові нетрі з популяцією благородних оленів та козуль. Джерело свіжого мʼяса та цінних шкур.',
  },
  {
    id: 'deposit-0-iron',
    type: 'iron',
    name: 'Залізна рудна жила',
    regionId: 0,
    gridPosition: [84, 32],
    position: [84.0, 0.15, 32.5],
    currentAmount: 280,
    maxAmount: 280,
    isRich: false,
    seasonalRenewal: false,
    icon: '⛏️',
    harvestBuildingLabel: 'Залізна копальня',
    description: 'Вихід багатої залізнякової породи на поверхню схилу пагорба. Сировина для виплавки металу та кування зброї.',
  },
  {
    id: 'deposit-0-salt',
    type: 'salt',
    name: 'Соляні джерела низовини',
    regionId: 0,
    gridPosition: [75, 85],
    position: [75.5, 0.08, 85.5],
    currentAmount: 180,
    maxAmount: 180,
    isRich: false,
    seasonalRenewal: false,
    icon: '🧂',
    harvestBuildingLabel: 'Солеварня',
    description: 'Мінералізовані підземні джерела для виварювання солі, необхідної для консервації продуктів на зиму.',
  },

  {
    id: 'deposit-1-game',
    type: 'wild_game',
    name: 'Багаті мисливські угіддя',
    regionId: 1,
    gridPosition: [330, 48],
    position: [330.5, 0.12, 48.5],
    currentAmount: 40,
    maxAmount: 40,
    isRich: true,
    seasonalRenewal: true,
    icon: '🦌',
    harvestBuildingLabel: 'Табір мисливців',
    description: 'Густий праліс із величезною популяцією благородних оленів та диких кабанів. Постачає цінне мʼясо та шкури.',
  },
  {
    id: 'deposit-1-fish',
    type: 'fish',
    name: 'Лісовий ставок Вальдау',
    regionId: 1,
    gridPosition: [320, 72],
    position: [320.5, 0.05, 72.5],
    currentAmount: 95,
    maxAmount: 95,
    isRich: false,
    seasonalRenewal: true,
    icon: '🐟',
    harvestBuildingLabel: 'Хатина рибалки',
    description: 'Глибоке лісове озеро, оточене віковими соснами. Річний ліміт вилову озерної форелі та окуня.',
  },
  {
    id: 'deposit-1-iron',
    type: 'iron',
    name: 'Поклади залізної руди',
    regionId: 1,
    gridPosition: [295, 38],
    position: [295.0, 0.14, 38.5],
    currentAmount: 240,
    maxAmount: 240,
    isRich: false,
    seasonalRenewal: false,
    icon: '⛏️',
    harvestBuildingLabel: 'Залізна шахта',
    description: 'Бура залізнякова жила, що залягає під лісовими пагорбами. Сировина для виплавки криці та кування мечів і броні.',
  },
  {
    id: 'deposit-1-berries',
    type: 'berries',
    name: 'Лісові ягідники',
    regionId: 1,
    gridPosition: [348, 85],
    position: [348.5, 0.1, 85.5],
    currentAmount: 64,
    maxAmount: 64,
    isRich: false,
    seasonalRenewal: true,
    icon: '🫐',
    harvestBuildingLabel: 'Хатина збирача ягід',
    description: 'Зарості лісової ожини та малини вздовж узлісся. Сезонне доповнення раціону місцевих жителів.',
  },
  {
    id: 'deposit-1-stone',
    type: 'stone',
    name: 'Скелястий виступ Вальдау',
    regionId: 1,
    gridPosition: [282, 78],
    position: [282.5, 0.18, 78.5],
    currentAmount: 260,
    maxAmount: 260,
    isRich: false,
    seasonalRenewal: false,
    icon: '🪨',
    harvestBuildingLabel: 'Каменоломня',
    description: 'Тверді кремʼяні та вапнякові валуни для будівництва баронських частоколів та камʼяниць.',
  },

  {
    id: 'deposit-2-fish',
    type: 'fish',
    name: 'Багата озерна затока Айхенау',
    regionId: 2,
    gridPosition: [60, 195],
    position: [60.5, 0.05, 195.5],
    currentAmount: 180,
    maxAmount: 180,
    isRich: true,
    seasonalRenewal: true,
    icon: '🐟',
    harvestBuildingLabel: 'Хатина рибалки',
    description: 'Велика спокійна затока з невичерпними зграями річкової риби. Багате родовище з подвійним річним лімітом вилову.',
  },
  {
    id: 'deposit-2-clay',
    type: 'clay',
    name: 'Багаті пласти гончарної глини',
    regionId: 2,
    gridPosition: [82, 250],
    position: [82.5, 0.08, 250.5],
    currentAmount: 380,
    maxAmount: 380,
    isRich: true,
    seasonalRenewal: false,
    icon: '🏺',
    harvestBuildingLabel: 'Глиняний карʼєр',
    description: 'Глибоке багате родовище тонкої червоної глини озерного походження. Ідеально для масового черепичного виробництва.',
  },
  {
    id: 'deposit-2-berries',
    type: 'berries',
    name: 'Ягідні луки',
    regionId: 2,
    gridPosition: [36, 242],
    position: [36.5, 0.1, 242.5],
    currentAmount: 64,
    maxAmount: 64,
    isRich: false,
    seasonalRenewal: true,
    icon: '🫐',
    harvestBuildingLabel: 'Хатина збирача ягід',
    description: 'Солодкі дикі ягоди на родючих заливних луках поблизу Айхенау.',
  },
  {
    id: 'deposit-2-salt',
    type: 'salt',
    name: 'Соляні джерела заплави',
    regionId: 2,
    gridPosition: [102, 260],
    position: [102.5, 0.12, 260.5],
    currentAmount: 160,
    maxAmount: 160,
    isRich: false,
    seasonalRenewal: false,
    icon: '🧂',
    harvestBuildingLabel: 'Солеварня',
    description: 'Мінералізоване соляне джерело. Сіль необхідна для соління риби, мʼяса та консервації провізії на зиму.',
  },

  {
    id: 'deposit-3-stone',
    type: 'stone',
    name: 'Багаті гірські каменоломні',
    regionId: 3,
    gridPosition: [258, 248],
    position: [258.5, 0.25, 248.5],
    currentAmount: 600,
    maxAmount: 600,
    isRich: true,
    seasonalRenewal: false,
    icon: '🪨',
    harvestBuildingLabel: 'Глибока каменоломня',
    description: 'Гігантський скельний розлом з гранітними та вапняковими монолітами. Багате родовище для спорудження неприступних фортець.',
  },
  {
    id: 'deposit-3-iron',
    type: 'iron',
    name: 'Багата залізорудна жила',
    regionId: 3,
    gridPosition: [315, 240],
    position: [315.0, 0.28, 240.5],
    currentAmount: 420,
    maxAmount: 420,
    isRich: true,
    seasonalRenewal: false,
    icon: '⛏️',
    harvestBuildingLabel: 'Глибока копальня',
    description: 'Товста жила високоякісного магнетиту та залізного колчедану. Дозволяє розвивати найпотужнішу зброярню у королівстві.',
  },
  {
    id: 'deposit-3-salt',
    type: 'salt',
    name: 'Багаті поклади камʼяної солі',
    regionId: 3,
    gridPosition: [248, 270],
    position: [248.5, 0.22, 270.5],
    currentAmount: 320,
    maxAmount: 320,
    isRich: true,
    seasonalRenewal: false,
    icon: '🧂',
    harvestBuildingLabel: 'Соляна шахта',
    description: 'Підземні пласти білої галітової солі. Стратегічний товар для торгівлі та забезпечення всіх сусідніх земель.',
  },
  {
    id: 'deposit-3-game',
    type: 'wild_game',
    name: 'Гірські мисливські пустки',
    regionId: 3,
    gridPosition: [335, 265],
    position: [335.5, 0.2, 265.5],
    currentAmount: 20,
    maxAmount: 20,
    isRich: false,
    seasonalRenewal: true,
    icon: '🦌',
    harvestBuildingLabel: 'Табір мисливців',
    description: 'Місця випасу гірських сарн та диких козлів серед камʼяних розсипів.',
  },

  {
    id: 'deposit-4-game',
    type: 'wild_game',
    name: 'Заповідні нетрі Міттенвальду',
    regionId: 4,
    gridPosition: [175, 45],
    position: [175.5, 0.12, 45.5],
    currentAmount: 50,
    maxAmount: 50,
    isRich: true,
    seasonalRenewal: true,
    icon: '🦌',
    harvestBuildingLabel: 'Хатина мисливця',
    description: 'Незаймані праліси з великою кількістю диких вепрів та оленів. Найкращі мисливські угіддя Середньовіччя.',
  },
  {
    id: 'deposit-4-berries',
    type: 'berries',
    name: 'Суничні галявини Міттенвальду',
    regionId: 4,
    gridPosition: [210, 80],
    position: [210.5, 0.1, 80.5],
    currentAmount: 80,
    maxAmount: 80,
    isRich: false,
    seasonalRenewal: true,
    icon: '🫐',
    harvestBuildingLabel: 'Хатина збирача ягід',
    description: 'Багаті лісові галявини дикої суниці та ожини вздовж гірських струмків.',
  },
  {
    id: 'deposit-4-stone',
    type: 'stone',
    name: 'Скелясті пагорби Міттенвальду',
    regionId: 4,
    gridPosition: [145, 60],
    position: [145.5, 0.16, 60.5],
    currentAmount: 280,
    maxAmount: 280,
    isRich: false,
    seasonalRenewal: false,
    icon: '🪨',
    harvestBuildingLabel: 'Каменоломня',
    description: 'Виходи міцного сірого каменю для будівництва міцних мурів та фундаментів.',
  },
  {
    id: 'deposit-4-iron',
    type: 'iron',
    name: 'Прихована залізна жила',
    regionId: 4,
    gridPosition: [235, 35],
    position: [235.0, 0.15, 35.5],
    currentAmount: 260,
    maxAmount: 260,
    isRich: false,
    seasonalRenewal: false,
    icon: '⛏️',
    harvestBuildingLabel: 'Залізна шахта',
    description: 'Рудна жила високоякісного залізняку в глибині лісових пагорбів.',
  },

  {
    id: 'deposit-5-stone',
    type: 'stone',
    name: 'Королівські придорожні карʼєри',
    regionId: 5,
    gridPosition: [120, 192],
    position: [120.5, 0.14, 192.5],
    currentAmount: 350,
    maxAmount: 350,
    isRich: false,
    seasonalRenewal: false,
    icon: '🪨',
    harvestBuildingLabel: 'Каменоломня',
    description: 'Виходи бруківкового каменю вздовж Тракту. Забезпечують бруківку та камʼяні верстові стовпи.',
  },
  {
    id: 'deposit-5-clay',
    type: 'clay',
    name: 'Притрактові глинища',
    regionId: 5,
    gridPosition: [270, 192],
    position: [270.5, 0.09, 192.5],
    currentAmount: 250,
    maxAmount: 250,
    isRich: false,
    seasonalRenewal: false,
    icon: '🏺',
    harvestBuildingLabel: 'Глиняний карʼєр',
    description: 'Поклади пластичної будівельної глини біля східного перехрестя.',
  },
];

export function initResourceDeposits(grid?: GridMap): ResourceDeposit[] {
  const existing = world.entities.filter((e) => e.isResourceDeposit);
  for (const e of existing) {
    world.remove(e);
  }

  const deposits: ResourceDeposit[] = JSON.parse(JSON.stringify(INITIAL_RESOURCE_DEPOSITS));

  for (const dep of deposits) {
    const [gx, gz] = dep.gridPosition;

    let h = dep.position[1];
    if (grid) {
      const tile = grid.getTile(gx, gz);
      if (tile) {
        h = dep.type === 'fish' ? 0.05 : Math.max(0.08, tile.height + 0.05);
        dep.position[1] = h;
      }

      if (dep.type !== 'fish') {
        const clearRadius = dep.type === 'berries' ? 1.5 : 2.8;
        const rSq = clearRadius * clearRadius;
        const maxR = Math.ceil(clearRadius);
        for (let dx = -maxR; dx <= maxR; dx++) {
          for (let dz = -maxR; dz <= maxR; dz++) {
            if (dx * dx + dz * dz <= rSq) {
              const tx = gx + dx;
              const tz = gz + dz;
              const t = grid.getTile(tx, tz);
              if (t && t.terrain !== 'water') {
                t.foliageType = undefined;
                t.foliageAngle = undefined;
                t.foliageTreeType = undefined;
                t.isPassable = true;
                t.movementCost = 1.0;
              }
            }
          }
        }
      }
    }

    world.add({
      id: dep.id,
      name: dep.name,
      isResourceDeposit: true,
      depositType: dep.type,
      regionId: dep.regionId,
      gridPosition: [gx, gz],
      position: [dep.position[0], h, dep.position[2]],
      resourceAmount: dep.currentAmount,
      maxResourceAmount: dep.maxAmount,
      isRichDeposit: dep.isRich,
      yearlyYield: dep.currentAmount,
      maxYearlyYield: dep.maxAmount,
      harvestBuildingLabel: dep.harvestBuildingLabel,
      depositDescription: dep.description,
      depositIcon: dep.icon,
    });
  }

  if (grid) {
    grid.refreshFoliageCoords();
  }

  return deposits;
}
