import type { BuildingBlueprint, BuildingType } from '../../types/game';

export const BUILDING_BLUEPRINTS: Record<BuildingType, BuildingBlueprint> = {
  lumberjack_hut: {
    type: 'lumberjack_hut',
    name: 'Хатина лісоруба',
    description: 'Робоче місце лісорубів. Призначені селяни (до 2 осіб) рубають дерева та заповнюють внутрішнє сховище (до 20 деревини). Коли сховище повне, рубка зупиняється.',
    width: 4,
    height: 2,
    cost: { wood: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 20,
    storageCapacity: { wood: 20 },
    health: 220,
    color: '#78350f',
  },
  tent: {
    type: 'tent',
    name: 'Палатка поселенців',
    description: 'Польовий прихисток для перших поселенців та правителя (до 3 осіб).',
    width: 3,
    height: 2,
    cost: { wood: 5 },
    category: 'housing',
    workSlots: 0,
    bedsCount: 3,
    health: 150,
    color: '#d97706',
  },
  campfire: {
    type: 'campfire',
    name: 'Вогнище поселення',
    description: 'Центр вашого поселення. Збирає поселенців для відпочинку та зігріває ночами.',
    width: 2,
    height: 2,
    cost: { wood: 5 },
    category: 'infrastructure',
    workSlots: 0,
    health: 100,
    color: '#ea580c',
  },
  hitching_post: {
    type: 'hitching_post',
    name: 'Прив\'язь для мулів',
    description: 'Стоянка для робочих мулів (до 3 мулів). Працівники складу беруть мула, щоб витягувати важкі колоди з лісоповалу та доставляти матеріали на будівельні майданчики.',
    width: 3,
    height: 2,
    cost: { wood: 5 },
    category: 'infrastructure',
    workSlots: 0,
    health: 150,
    color: '#854d0e',
  },
  peasant_house: {
    type: 'peasant_house',
    name: 'Хатина селян',
    description: 'Просторий середньовічний будинок на 3 мешканців із кам\'яним каміном та затишним інтер\'єром. Відновлює сили та дає прихисток новим селянам.',
    width: 4,
    height: 2,
    cost: { wood: 15 },
    category: 'housing',
    workSlots: 0,
    bedsCount: 3,
    health: 280,
    color: '#a16207',
  },
  manor: {
    type: 'manor',
    name: 'Маєток Лорда',
    description: 'Розкішна резиденція для монарха та шляхти. Підвищує лояльність та авторитет.',
    width: 5,
    height: 4,
    cost: { wood: 60, stone: 40, gold: 50 },
    category: 'housing',
    workSlots: 2,
    health: 600,
    color: '#4338ca',
  },
  stockpile: {
    type: 'stockpile',
    name: 'Склад ресурсів',
    description: 'Центральний склад поселення. Призначені носії (до 4 осіб) обходять лісопилки, хатини мисливців, копальні та інші споруди, забирають накопичені ресурси та звозять їх на склад.',
    width: 4,
    height: 2,
    cost: { wood: 10 },
    category: 'infrastructure',
    workSlots: 4,
    defaultWage: 2,
    maxStorage: 200,
    health: 200,
    color: '#ca8a04',
  },
  market: {
    type: 'market',
    name: 'Ринок поселення',
    description: 'Центр обігу грошей. Селяни купують тут хліб та ель за зароблені монети, повертаючи капітал до вашої скарбниці.',
    width: 4,
    height: 2,
    cost: { wood: 20, stone: 5 },
    category: 'infrastructure',
    workSlots: 1,
    defaultWage: 2,
    health: 220,
    color: '#10b981',
  },
  wheat_farm: {
    type: 'wheat_farm',
    name: 'Пшеничне поле',
    description: 'Ділянка для вирощування зерна на родючому ґрунті.',
    width: 4,
    height: 4,
    cost: { wood: 10 },
    category: 'agriculture',
    workSlots: 3,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { wheat: 30 },
    health: 150,
    color: '#eab308',
    produces: {
      inputs: {},
      outputs: { wheat: 15 },
      ticksRequired: 100,
    },
  },
  windmill: {
    type: 'windmill',
    name: 'Млин',
    description: 'Перемелює зібрану пшеницю на борошно для пекарні.',
    width: 3,
    height: 3,
    cost: { wood: 35, stone: 15 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { flour: 30 },
    health: 300,
    color: '#d97706',
    produces: {
      inputs: { wheat: 5 },
      outputs: { flour: 5 },
      ticksRequired: 40,
    },
  },
  bakery: {
    type: 'bakery',
    name: 'Пекарня',
    description: 'Випікає поживний хліб із борошна для продажу селянам на ринку.',
    width: 4,
    height: 2,
    cost: { wood: 25, stone: 20 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { bread: 30 },
    health: 280,
    color: '#b45309',
    produces: {
      inputs: { flour: 4, wood: 1 },
      outputs: { bread: 6 },
      ticksRequired: 30,
    },
  },
  brewery: {
    type: 'brewery',
    name: 'Пивоварня',
    description: 'Варить запашний середньовічний ель. Задовольняє жагу та приносить прибуток на ринку.',
    width: 4,
    height: 2,
    cost: { wood: 30, stone: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { ale: 30 },
    health: 260,
    color: '#92400e',
    produces: {
      inputs: { wheat: 4, wood: 1 },
      outputs: { ale: 5 },
      ticksRequired: 50,
    },
  },
  barracks: {
    type: 'barracks',
    name: 'Казарми',
    description: 'Тренує воїнів та зберігає мечі й обладунки для захисту від розбійників.',
    width: 5,
    height: 3,
    cost: { wood: 45, stone: 30 },
    category: 'military',
    workSlots: 3,
    health: 500,
    color: '#991b1b',
  },
  wooden_wall: {
    type: 'wooden_wall',
    name: 'Дерев’яний частокіл',
    description: 'Захисна стіна, що перекриває прохід ворогам.',
    width: 1,
    height: 1,
    cost: { wood: 3 },
    category: 'infrastructure',
    workSlots: 0,
    health: 120,
    color: '#78350f',
  },
  wooden_gate: {
    type: 'wooden_gate',
    name: 'Дерев’яна брама',
    description: 'Прохідна брама для жителів поселення.',
    width: 1,
    height: 1,
    cost: { wood: 6 },
    category: 'infrastructure',
    workSlots: 0,
    health: 150,
    color: '#9a3412',
  },
  stone_wall: {
    type: 'stone_wall',
    name: 'Кам’яна стіна',
    description: 'Міцна фортифікаційна споруда.',
    width: 1,
    height: 1,
    cost: { stone: 6 },
    category: 'infrastructure',
    workSlots: 0,
    health: 400,
    color: '#64748b',
  },
  fishermans_hut: {
    type: 'fishermans_hut',
    name: 'Хатина рибалки',
    description: 'Рибальська пристань і хатина на палях. Призначені рибалки ловлять свіжу рибу біля води та заповнюють сховище.',
    width: 4,
    height: 3,
    cost: { wood: 15 },
    category: 'gathering',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { fish: 30 },
    health: 200,
    color: '#0284c7',
  },
  foragers_hut: {
    type: 'foragers_hut',
    name: 'Хатина збирачів ягід',
    description: 'Пункт заготівлі лісових дарів. Збирачі прямують до найближчих ягідних чагарників та постачають свіжі ягоди.',
    width: 4,
    height: 3,
    cost: { wood: 10 },
    category: 'gathering',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { berries: 30 },
    health: 180,
    color: '#7c3aed',
  },
  hunters_hut: {
    type: 'hunters_hut',
    name: 'Хатина мисливця',
    description: 'Мисливський табір у лісі. Мисливці відстежують дичину в мисливських угіддях, видобуваючи поживне мʼясо та шкури.',
    width: 4,
    height: 3,
    cost: { wood: 15 },
    category: 'gathering',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { meat: 20, hides: 10 },
    health: 220,
    color: '#15803d',
  },
  iron_mine: {
    type: 'iron_mine',
    name: 'Залізна копальня',
    description: 'Шахта для видобування залізної руди. Зводиться виключно поруч із родовищами заліза.',
    width: 4,
    height: 3,
    cost: { wood: 30, stone: 15 },
    category: 'production',
    workSlots: 3,
    defaultWage: 3,
    maxStorage: 40,
    storageCapacity: { iron_ore: 40 },
    health: 350,
    color: '#475569',
    produces: {
      inputs: {},
      outputs: { iron_ore: 5 },
      ticksRequired: 50,
    },
  },
  stone_quarry: {
    type: 'stone_quarry',
    name: 'Каменоломня',
    description: 'Карʼєр для видобування блоків будівельного каменю. Зводиться виключно поруч із покладами каменю.',
    width: 4,
    height: 3,
    cost: { wood: 25 },
    category: 'production',
    workSlots: 3,
    defaultWage: 2,
    maxStorage: 40,
    storageCapacity: { stone: 40 },
    health: 300,
    color: '#64748b',
    produces: {
      inputs: {},
      outputs: { stone: 6 },
      ticksRequired: 40,
    },
  },
  clay_pit: {
    type: 'clay_pit',
    name: 'Глиняний карʼєр',
    description: 'Розробка пластичних пластів глини. Зводиться виключно поруч із покладами глини.',
    width: 4,
    height: 3,
    cost: { wood: 20 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 40,
    storageCapacity: { clay: 40 },
    health: 250,
    color: '#c2410c',
    produces: {
      inputs: {},
      outputs: { clay: 5 },
      ticksRequired: 45,
    },
  },
  salt_works: {
    type: 'salt_works',
    name: 'Солеварня',
    description: 'Підприємство для виварювання харчової солі. Зводиться виключно поруч із соляними джерелами.',
    width: 4,
    height: 3,
    cost: { wood: 30, stone: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 40,
    storageCapacity: { salt: 40 },
    health: 260,
    color: '#e2e8f0',
    produces: {
      inputs: { wood: 1 },
      outputs: { salt: 4 },
      ticksRequired: 45,
    },
  },
  charcoal_kiln: {
    type: 'charcoal_kiln',
    name: 'Вугільна піч',
    description: 'Піч для перепалювання колод у деревне вугілля для плавилень, цегелень та обігріву.',
    width: 5,
    height: 3,
    cost: { wood: 15, stone: 20 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { coal: 30 },
    health: 280,
    color: '#1e293b',
    produces: {
      inputs: { wood: 3 },
      outputs: { coal: 3 },
      ticksRequired: 35,
    },
  },
  iron_smelter: {
    type: 'iron_smelter',
    name: 'Плавильня заліза',
    description: 'Виплавляє очищене сортове залізо із залізної руди та вугілля.',
    width: 5,
    height: 3,
    cost: { wood: 35, stone: 35 },
    category: 'production',
    workSlots: 2,
    defaultWage: 3,
    maxStorage: 30,
    storageCapacity: { iron: 30 },
    health: 320,
    color: '#b91c1c',
    produces: {
      inputs: { iron_ore: 2, coal: 1 },
      outputs: { iron: 2 },
      ticksRequired: 45,
    },
  },
  stonecutter: {
    type: 'stonecutter',
    name: 'Майстерня каменяра',
    description: 'Теше необроблений камінь на рівні будівельні плити та блоки.',
    width: 5,
    height: 3,
    cost: { wood: 20, stone: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { cut_stone: 30 },
    health: 260,
    color: '#475569',
    produces: {
      inputs: { stone: 3 },
      outputs: { cut_stone: 3 },
      ticksRequired: 35,
    },
  },
  brickworks: {
    type: 'brickworks',
    name: 'Цегельня',
    description: 'Випалює глиняну цеглу та покрівельну черепицю з використанням вугілля.',
    width: 5,
    height: 3,
    cost: { wood: 25, stone: 25 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { clay_bricks: 30 },
    health: 290,
    color: '#9a3412',
    produces: {
      inputs: { clay: 3, coal: 1 },
      outputs: { clay_bricks: 3 },
      ticksRequired: 40,
    },
  },
  sawmill: {
    type: 'sawmill',
    name: 'Тартак',
    description: 'Розпилює стовбури дерев на високоякісні дошки для будівельних робіт.',
    width: 5,
    height: 3,
    cost: { wood: 40, stone: 15 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 40,
    storageCapacity: { planks: 40 },
    health: 300,
    color: '#854d0e',
    produces: {
      inputs: { wood: 2 },
      outputs: { planks: 4 },
      ticksRequired: 30,
    },
  },
  weavers_workshop: {
    type: 'weavers_workshop',
    name: 'Ткацька майстерня',
    description: 'Виготовляє теплий повсякденний одяг зі шкур та полотна.',
    width: 4,
    height: 3,
    cost: { wood: 25, stone: 10 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 30,
    storageCapacity: { clothes: 30 },
    health: 240,
    color: '#0d9488',
    produces: {
      inputs: { hides: 2 },
      outputs: { clothes: 2 },
      ticksRequired: 40,
    },
  },
  foresters_hut: {
    type: 'foresters_hut',
    name: 'Хатина лісника',
    description: 'Відновлює лісові масиви, висаджуючи молоді саджанці на вирубаних галявинах.',
    width: 4,
    height: 3,
    cost: { wood: 15 },
    category: 'production',
    workSlots: 2,
    defaultWage: 2,
    health: 200,
    color: '#166534',
  },
  wooden_church: {
    type: 'wooden_church',
    name: 'Дерев’яна церква',
    description: 'Осередок духовності та спокою. Задовольняє релігійні потреби мешканців та підвищує настрій усьому поселенню.',
    width: 5,
    height: 3,
    cost: { wood: 50, stone: 30, gold: 20 },
    category: 'community',
    workSlots: 1,
    defaultWage: 3,
    health: 450,
    color: '#d97706',
  },
  tavern: {
    type: 'tavern',
    name: 'Корчма',
    description: 'Заклад відпочинку та частування. Споживає ель, приносить золотий дохід та дарує радість поселенцям.',
    width: 4,
    height: 3,
    cost: { wood: 35, stone: 15, gold: 15 },
    category: 'community',
    workSlots: 2,
    defaultWage: 2,
    health: 300,
    color: '#b45309',
  },
  trading_post: {
    type: 'trading_post',
    name: 'Торговий пункт',
    description: 'Осередок зовнішньої торгівлі. Дозволяє налаштовувати імпорт та експорт товарів. Щодня між 10:00 та 15:00 сюди прибувають мандрівні купці з возом та конем для здійснення угод.',
    width: 5,
    height: 3,
    cost: { wood: 30, stone: 15 },
    category: 'infrastructure',
    workSlots: 2,
    defaultWage: 2,
    maxStorage: 150,
    health: 350,
    color: '#ca8a04',
  },
};
